/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

/**
 *
 * @author kevin
 */
public class Maestro extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Maestro() {
        initComponents();
        this.FondoVerPublicacion.setVisible(false);
        this.FondoEdit.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayeredPane = new javax.swing.JLayeredPane();
        FondoVerPublicacion = new javax.swing.JPanel();
        EditarPublicacion = new javax.swing.JButton();
        PublicacionVolver = new javax.swing.JButton();
        jScrollPanePubli = new javax.swing.JScrollPane();
        jTextAreaPubli = new javax.swing.JTextArea();
        jScrollPaneComent = new javax.swing.JScrollPane();
        jTextAreaComent = new javax.swing.JTextArea();
        EliminarPublicacion = new javax.swing.JButton();
        jScrollPaneTitulo = new javax.swing.JScrollPane();
        jTextAreaTitulo = new javax.swing.JTextArea();
        FondoInicioMaestro = new javax.swing.JPanel();
        InicioAprendiz = new javax.swing.JPanel();
        CuentaBtn = new javax.swing.JButton();
        GuardadasBtn = new javax.swing.JButton();
        CarrarSesionBtn = new javax.swing.JButton();
        jScrollPaneInicio = new javax.swing.JScrollPane();
        FondoEdit = new javax.swing.JPanel();
        ConfirmarEdit = new javax.swing.JButton();
        CancelarEdit = new javax.swing.JButton();
        jScrollPanePubliEdit = new javax.swing.JScrollPane();
        jTextAreaPubliEdit = new javax.swing.JTextArea();
        jScrollPaneTituloEdit = new javax.swing.JScrollPane();
        jTextAreaTituloEdit = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1288, 696));
        setSize(new java.awt.Dimension(1288, 696));

        FondoVerPublicacion.setBackground(new java.awt.Color(25, 37, 77));
        FondoVerPublicacion.setEnabled(false);
        FondoVerPublicacion.setFocusable(false);

        EditarPublicacion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        EditarPublicacion.setText("Editar");
        EditarPublicacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        EditarPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPublicacionActionPerformed(evt);
            }
        });

        PublicacionVolver.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        PublicacionVolver.setText("Volver");
        PublicacionVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        PublicacionVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublicacionVolverActionPerformed(evt);
            }
        });

        jTextAreaPubli.setEditable(false);
        jTextAreaPubli.setColumns(20);
        jTextAreaPubli.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jTextAreaPubli.setRows(5);
        jTextAreaPubli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextAreaPubli.setFocusable(false);
        jScrollPanePubli.setViewportView(jTextAreaPubli);

        jTextAreaComent.setEditable(false);
        jTextAreaComent.setColumns(10);
        jTextAreaComent.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextAreaComent.setRows(5);
        jTextAreaComent.setText("\n");
        jTextAreaComent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextAreaComent.setFocusable(false);
        jScrollPaneComent.setViewportView(jTextAreaComent);

        EliminarPublicacion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        EliminarPublicacion.setText("Eliminar");
        EliminarPublicacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        EliminarPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarPublicacionActionPerformed(evt);
            }
        });

        jScrollPaneTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jTextAreaTitulo.setEditable(false);
        jTextAreaTitulo.setColumns(20);
        jTextAreaTitulo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jTextAreaTitulo.setRows(1);
        jTextAreaTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jScrollPaneTitulo.setViewportView(jTextAreaTitulo);

        javax.swing.GroupLayout FondoVerPublicacionLayout = new javax.swing.GroupLayout(FondoVerPublicacion);
        FondoVerPublicacion.setLayout(FondoVerPublicacionLayout);
        FondoVerPublicacionLayout.setHorizontalGroup(
            FondoVerPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoVerPublicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneComent, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoVerPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoVerPublicacionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(EditarPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191)
                        .addComponent(EliminarPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198)
                        .addComponent(PublicacionVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPanePubli))
                .addContainerGap())
        );
        FondoVerPublicacionLayout.setVerticalGroup(
            FondoVerPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerPublicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoVerPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoVerPublicacionLayout.createSequentialGroup()
                        .addComponent(jScrollPaneTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPanePubli, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FondoVerPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PublicacionVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditarPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EliminarPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPaneComent))
                .addGap(18, 18, 18))
        );

        FondoInicioMaestro.setBackground(new java.awt.Color(25, 37, 77));

        InicioAprendiz.setBackground(new java.awt.Color(67, 72, 121));
        InicioAprendiz.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        CuentaBtn.setBackground(new java.awt.Color(200, 191, 191));
        CuentaBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        CuentaBtn.setText("Editar Cuenta");
        CuentaBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        GuardadasBtn.setBackground(new java.awt.Color(200, 191, 191));
        GuardadasBtn.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        GuardadasBtn.setText("Crear Publicación");
        GuardadasBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        GuardadasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardadasBtnActionPerformed(evt);
            }
        });

        CarrarSesionBtn.setBackground(new java.awt.Color(200, 191, 191));
        CarrarSesionBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        CarrarSesionBtn.setText("Cerrar Sesión");
        CarrarSesionBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout InicioAprendizLayout = new javax.swing.GroupLayout(InicioAprendiz);
        InicioAprendiz.setLayout(InicioAprendizLayout);
        InicioAprendizLayout.setHorizontalGroup(
            InicioAprendizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioAprendizLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(CuentaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(InicioAprendizLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InicioAprendizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CarrarSesionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuardadasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InicioAprendizLayout.setVerticalGroup(
            InicioAprendizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioAprendizLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(CuentaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(GuardadasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CarrarSesionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jScrollPaneInicio.setBackground(new java.awt.Color(25, 37, 77));
        jScrollPaneInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout FondoInicioMaestroLayout = new javax.swing.GroupLayout(FondoInicioMaestro);
        FondoInicioMaestro.setLayout(FondoInicioMaestroLayout);
        FondoInicioMaestroLayout.setHorizontalGroup(
            FondoInicioMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoInicioMaestroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InicioAprendiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jScrollPaneInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
                .addContainerGap())
        );
        FondoInicioMaestroLayout.setVerticalGroup(
            FondoInicioMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoInicioMaestroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoInicioMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InicioAprendiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(FondoInicioMaestroLayout.createSequentialGroup()
                        .addComponent(jScrollPaneInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );

        FondoEdit.setBackground(new java.awt.Color(25, 37, 77));
        FondoEdit.setEnabled(false);
        FondoEdit.setFocusable(false);

        ConfirmarEdit.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ConfirmarEdit.setText("Editar");
        ConfirmarEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ConfirmarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarEditActionPerformed(evt);
            }
        });

        CancelarEdit.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        CancelarEdit.setText("Cancelar");
        CancelarEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        CancelarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarEditActionPerformed(evt);
            }
        });

        jTextAreaPubliEdit.setColumns(20);
        jTextAreaPubliEdit.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jTextAreaPubliEdit.setRows(5);
        jTextAreaPubliEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jScrollPanePubliEdit.setViewportView(jTextAreaPubliEdit);

        jScrollPaneTituloEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jTextAreaTituloEdit.setColumns(20);
        jTextAreaTituloEdit.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jTextAreaTituloEdit.setRows(1);
        jTextAreaTituloEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jScrollPaneTituloEdit.setViewportView(jTextAreaTituloEdit);

        javax.swing.GroupLayout FondoEditLayout = new javax.swing.GroupLayout(FondoEdit);
        FondoEdit.setLayout(FondoEditLayout);
        FondoEditLayout.setHorizontalGroup(
            FondoEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoEditLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(ConfirmarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284)
                .addComponent(CancelarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoEditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FondoEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPanePubliEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                    .addComponent(jScrollPaneTituloEdit))
                .addGap(154, 154, 154))
        );
        FondoEditLayout.setVerticalGroup(
            FondoEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTituloEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPanePubliEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        LayeredPane.setLayer(FondoVerPublicacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPane.setLayer(FondoInicioMaestro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPane.setLayer(FondoEdit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayeredPaneLayout = new javax.swing.GroupLayout(LayeredPane);
        LayeredPane.setLayout(LayeredPaneLayout);
        LayeredPaneLayout.setHorizontalGroup(
            LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoVerPublicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FondoInicioMaestro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FondoEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LayeredPaneLayout.setVerticalGroup(
            LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoVerPublicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FondoInicioMaestro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FondoEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayeredPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayeredPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardadasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardadasBtnActionPerformed
        this.FondoInicioMaestro.setEnabled(false);
        this.FondoInicioMaestro.setFocusable(false);
        this.FondoInicioMaestro.setVisible(false);
        this.FondoVerPublicacion.setEnabled(true);
        this.FondoVerPublicacion.setFocusable(true);
        this.FondoVerPublicacion.setVisible(true);
    }//GEN-LAST:event_GuardadasBtnActionPerformed

    private void PublicacionVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublicacionVolverActionPerformed
        this.FondoInicioMaestro.setEnabled(true);
        this.FondoInicioMaestro.setFocusable(true);
        this.FondoInicioMaestro.setVisible(true);
        this.FondoVerPublicacion.setEnabled(false);
        this.FondoVerPublicacion.setFocusable(false);
        this.FondoVerPublicacion.setVisible(false);
    }//GEN-LAST:event_PublicacionVolverActionPerformed

    private void CancelarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarEditActionPerformed
        this.FondoVerPublicacion.setEnabled(true);
        this.FondoVerPublicacion.setFocusable(true);
        this.FondoVerPublicacion.setVisible(true);
        this.FondoEdit.setEnabled(false);
        this.FondoEdit.setFocusable(false);
        this.FondoEdit.setVisible(false);
    }//GEN-LAST:event_CancelarEditActionPerformed

    private void EditarPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPublicacionActionPerformed
        this.FondoVerPublicacion.setEnabled(false);
        this.FondoVerPublicacion.setFocusable(false);
        this.FondoVerPublicacion.setVisible(false);
        this.FondoEdit.setEnabled(true);
        this.FondoEdit.setFocusable(true);
        this.FondoEdit.setVisible(true);
        this.jTextAreaTituloEdit.setText(this.jTextAreaTitulo.getText());
        this.jTextAreaPubliEdit.setText(this.jTextAreaPubli.getText());
    }//GEN-LAST:event_EditarPublicacionActionPerformed

    private void ConfirmarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarEditActionPerformed
        this.FondoVerPublicacion.setEnabled(true);
        this.FondoVerPublicacion.setFocusable(true);
        this.FondoVerPublicacion.setVisible(true);
        this.FondoEdit.setEnabled(false);
        this.FondoEdit.setFocusable(false);
        this.FondoEdit.setVisible(false);
        this.jTextAreaTitulo.setText(this.jTextAreaTituloEdit.getText());
        this.jTextAreaPubli.setText(this.jTextAreaPubliEdit.getText());
    }//GEN-LAST:event_ConfirmarEditActionPerformed

    private void EliminarPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarPublicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarPublicacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maestro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarEdit;
    private javax.swing.JButton CarrarSesionBtn;
    private javax.swing.JButton ConfirmarEdit;
    private javax.swing.JButton CuentaBtn;
    private javax.swing.JButton EditarPublicacion;
    private javax.swing.JButton EliminarPublicacion;
    private javax.swing.JPanel FondoEdit;
    private javax.swing.JPanel FondoInicioMaestro;
    private javax.swing.JPanel FondoVerPublicacion;
    private javax.swing.JButton GuardadasBtn;
    private javax.swing.JPanel InicioAprendiz;
    private javax.swing.JLayeredPane LayeredPane;
    private javax.swing.JButton PublicacionVolver;
    private javax.swing.JScrollPane jScrollPaneComent;
    private javax.swing.JScrollPane jScrollPaneInicio;
    private javax.swing.JScrollPane jScrollPanePubli;
    private javax.swing.JScrollPane jScrollPanePubliEdit;
    private javax.swing.JScrollPane jScrollPaneTitulo;
    private javax.swing.JScrollPane jScrollPaneTituloEdit;
    private javax.swing.JTextArea jTextAreaComent;
    private javax.swing.JTextArea jTextAreaPubli;
    private javax.swing.JTextArea jTextAreaPubliEdit;
    private javax.swing.JTextArea jTextAreaTitulo;
    private javax.swing.JTextArea jTextAreaTituloEdit;
    // End of variables declaration//GEN-END:variables
}
