/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import ConexionDB.Controller;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import reque.Publicacion;
import reque.User;

/**
 *
 * @author kevin
 */
public class Maestro extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    User usuario;
    Controller control;
    Publicacion PubliActual = null;
    public Maestro(User usuario, Controller control) {
        initComponents();
        this.FondoVerPublicacion.setVisible(false);
        this.FondoEdit.setVisible(false);
        this.FondoCrearP.setVisible(false);
        this.usuario = usuario;
        this.control = control;
        this.Post(this.usuario.getName(), 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayeredPane = new javax.swing.JLayeredPane();
        FondoVerPublicacion = new javax.swing.JPanel();
        EditarPublicacion = new javax.swing.JButton();
        PublicacionVolver = new javax.swing.JButton();
        jScrollPanePubli = new javax.swing.JScrollPane();
        jTextAreaPubli = new javax.swing.JTextArea();
        jScrollPaneComent = new javax.swing.JScrollPane();
        jTextAreaComent = new javax.swing.JTextArea();
        EliminarPublicacion = new javax.swing.JButton();
        jScrollPaneTitulo = new javax.swing.JScrollPane();
        jTextAreaTitulo = new javax.swing.JTextArea();
        FondoInicioMaestro = new javax.swing.JPanel();
        InicioAprendiz = new javax.swing.JPanel();
        CuentaBtn = new javax.swing.JButton();
        CrearBtn = new javax.swing.JButton();
        CarrarSesionBtn = new javax.swing.JButton();
        jScrollPaneInicio = new javax.swing.JScrollPane();
        jPanelInicio = new javax.swing.JPanel();
        FondoEdit = new javax.swing.JPanel();
        ConfirmarEdit = new javax.swing.JButton();
        CancelarEdit = new javax.swing.JButton();
        jScrollPanePubliEdit = new javax.swing.JScrollPane();
        jTextAreaPubliEdit = new javax.swing.JTextArea();
        jScrollPaneTituloEdit = new javax.swing.JScrollPane();
        jTextAreaTituloEdit = new javax.swing.JTextArea();
        FondoCrearP = new javax.swing.JPanel();
        ConfirmarCrearP = new javax.swing.JButton();
        CancelarCrearP = new javax.swing.JButton();
        jScrollPanePubliCrearP = new javax.swing.JScrollPane();
        jTextAreaPubliCrearP = new javax.swing.JTextArea();
        jScrollPaneTituloCrearP = new javax.swing.JScrollPane();
        jTextAreaTituloCrearP = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1288, 696));
        setSize(new java.awt.Dimension(1288, 696));

        FondoVerPublicacion.setBackground(new java.awt.Color(25, 37, 77));
        FondoVerPublicacion.setEnabled(false);
        FondoVerPublicacion.setFocusable(false);

        EditarPublicacion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        EditarPublicacion.setText("Editar");
        EditarPublicacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        EditarPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPublicacionActionPerformed(evt);
            }
        });

        PublicacionVolver.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        PublicacionVolver.setText("Volver");
        PublicacionVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        PublicacionVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublicacionVolverActionPerformed(evt);
            }
        });

        jTextAreaPubli.setEditable(false);
        jTextAreaPubli.setColumns(20);
        jTextAreaPubli.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jTextAreaPubli.setRows(5);
        jTextAreaPubli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextAreaPubli.setFocusable(false);
        jScrollPanePubli.setViewportView(jTextAreaPubli);

        jTextAreaComent.setEditable(false);
        jTextAreaComent.setColumns(10);
        jTextAreaComent.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextAreaComent.setRows(5);
        jTextAreaComent.setText("\n");
        jTextAreaComent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextAreaComent.setFocusable(false);
        jScrollPaneComent.setViewportView(jTextAreaComent);

        EliminarPublicacion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        EliminarPublicacion.setText("Eliminar");
        EliminarPublicacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        EliminarPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarPublicacionActionPerformed(evt);
            }
        });

        jScrollPaneTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jTextAreaTitulo.setEditable(false);
        jTextAreaTitulo.setColumns(20);
        jTextAreaTitulo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jTextAreaTitulo.setRows(1);
        jTextAreaTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jScrollPaneTitulo.setViewportView(jTextAreaTitulo);

        javax.swing.GroupLayout FondoVerPublicacionLayout = new javax.swing.GroupLayout(FondoVerPublicacion);
        FondoVerPublicacion.setLayout(FondoVerPublicacionLayout);
        FondoVerPublicacionLayout.setHorizontalGroup(
            FondoVerPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoVerPublicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneComent, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoVerPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoVerPublicacionLayout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addComponent(EditarPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191)
                        .addComponent(EliminarPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198)
                        .addComponent(PublicacionVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPanePubli))
                .addContainerGap())
        );
        FondoVerPublicacionLayout.setVerticalGroup(
            FondoVerPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerPublicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoVerPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoVerPublicacionLayout.createSequentialGroup()
                        .addComponent(jScrollPaneTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPanePubli, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FondoVerPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PublicacionVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditarPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EliminarPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPaneComent))
                .addGap(18, 18, 18))
        );

        FondoInicioMaestro.setBackground(new java.awt.Color(25, 37, 77));

        InicioAprendiz.setBackground(new java.awt.Color(67, 72, 121));
        InicioAprendiz.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        CuentaBtn.setBackground(new java.awt.Color(200, 191, 191));
        CuentaBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        CuentaBtn.setText("Editar Cuenta");
        CuentaBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        CrearBtn.setBackground(new java.awt.Color(200, 191, 191));
        CrearBtn.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        CrearBtn.setText("Crear Publicación");
        CrearBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        CrearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBtnActionPerformed(evt);
            }
        });

        CarrarSesionBtn.setBackground(new java.awt.Color(200, 191, 191));
        CarrarSesionBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        CarrarSesionBtn.setText("Cerrar Sesión");
        CarrarSesionBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        CarrarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrarSesionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InicioAprendizLayout = new javax.swing.GroupLayout(InicioAprendiz);
        InicioAprendiz.setLayout(InicioAprendizLayout);
        InicioAprendizLayout.setHorizontalGroup(
            InicioAprendizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioAprendizLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(CuentaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(InicioAprendizLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InicioAprendizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CarrarSesionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InicioAprendizLayout.setVerticalGroup(
            InicioAprendizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioAprendizLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(CuentaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(CrearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CarrarSesionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jScrollPaneInicio.setBackground(new java.awt.Color(25, 37, 77));
        jScrollPaneInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jPanelInicio.setBackground(new java.awt.Color(25, 37, 77));
        jPanelInicio.setAutoscrolls(true);
        jPanelInicio.setLayout(new java.awt.GridLayout(100, 0, 0, 25));
        jScrollPaneInicio.setViewportView(jPanelInicio);

        javax.swing.GroupLayout FondoInicioMaestroLayout = new javax.swing.GroupLayout(FondoInicioMaestro);
        FondoInicioMaestro.setLayout(FondoInicioMaestroLayout);
        FondoInicioMaestroLayout.setHorizontalGroup(
            FondoInicioMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoInicioMaestroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InicioAprendiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jScrollPaneInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
                .addContainerGap())
        );
        FondoInicioMaestroLayout.setVerticalGroup(
            FondoInicioMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoInicioMaestroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoInicioMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InicioAprendiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(FondoInicioMaestroLayout.createSequentialGroup()
                        .addComponent(jScrollPaneInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );

        FondoEdit.setBackground(new java.awt.Color(25, 37, 77));
        FondoEdit.setEnabled(false);
        FondoEdit.setFocusable(false);

        ConfirmarEdit.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ConfirmarEdit.setText("Editar");
        ConfirmarEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ConfirmarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarEditActionPerformed(evt);
            }
        });

        CancelarEdit.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        CancelarEdit.setText("Cancelar");
        CancelarEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        CancelarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarEditActionPerformed(evt);
            }
        });

        jTextAreaPubliEdit.setColumns(20);
        jTextAreaPubliEdit.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jTextAreaPubliEdit.setRows(5);
        jTextAreaPubliEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jScrollPanePubliEdit.setViewportView(jTextAreaPubliEdit);

        jScrollPaneTituloEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jTextAreaTituloEdit.setColumns(20);
        jTextAreaTituloEdit.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jTextAreaTituloEdit.setRows(1);
        jTextAreaTituloEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jScrollPaneTituloEdit.setViewportView(jTextAreaTituloEdit);

        javax.swing.GroupLayout FondoEditLayout = new javax.swing.GroupLayout(FondoEdit);
        FondoEdit.setLayout(FondoEditLayout);
        FondoEditLayout.setHorizontalGroup(
            FondoEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoEditLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(ConfirmarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284)
                .addComponent(CancelarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoEditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FondoEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPanePubliEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                    .addComponent(jScrollPaneTituloEdit))
                .addGap(154, 154, 154))
        );
        FondoEditLayout.setVerticalGroup(
            FondoEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTituloEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPanePubliEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        FondoCrearP.setBackground(new java.awt.Color(25, 37, 77));
        FondoCrearP.setEnabled(false);
        FondoCrearP.setFocusable(false);

        ConfirmarCrearP.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ConfirmarCrearP.setText("Confirmar");
        ConfirmarCrearP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ConfirmarCrearP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarCrearPActionPerformed(evt);
            }
        });

        CancelarCrearP.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        CancelarCrearP.setText("Cancelar");
        CancelarCrearP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        CancelarCrearP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarCrearPActionPerformed(evt);
            }
        });

        jTextAreaPubliCrearP.setColumns(20);
        jTextAreaPubliCrearP.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jTextAreaPubliCrearP.setRows(5);
        jTextAreaPubliCrearP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jScrollPanePubliCrearP.setViewportView(jTextAreaPubliCrearP);

        jScrollPaneTituloCrearP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jTextAreaTituloCrearP.setColumns(20);
        jTextAreaTituloCrearP.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jTextAreaTituloCrearP.setRows(1);
        jTextAreaTituloCrearP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jScrollPaneTituloCrearP.setViewportView(jTextAreaTituloCrearP);

        javax.swing.GroupLayout FondoCrearPLayout = new javax.swing.GroupLayout(FondoCrearP);
        FondoCrearP.setLayout(FondoCrearPLayout);
        FondoCrearPLayout.setHorizontalGroup(
            FondoCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoCrearPLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(ConfirmarCrearP, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284)
                .addComponent(CancelarCrearP, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoCrearPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FondoCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPanePubliCrearP)
                    .addComponent(jScrollPaneTituloCrearP, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE))
                .addGap(154, 154, 154))
        );
        FondoCrearPLayout.setVerticalGroup(
            FondoCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoCrearPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTituloCrearP, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPanePubliCrearP, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmarCrearP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelarCrearP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        LayeredPane.setLayer(FondoVerPublicacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPane.setLayer(FondoInicioMaestro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPane.setLayer(FondoEdit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPane.setLayer(FondoCrearP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayeredPaneLayout = new javax.swing.GroupLayout(LayeredPane);
        LayeredPane.setLayout(LayeredPaneLayout);
        LayeredPaneLayout.setHorizontalGroup(
            LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoVerPublicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FondoInicioMaestro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FondoEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FondoCrearP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LayeredPaneLayout.setVerticalGroup(
            LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoVerPublicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FondoInicioMaestro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FondoEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FondoCrearP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayeredPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayeredPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBtnActionPerformed
        this.FondoInicioMaestro.setEnabled(false);
        this.FondoInicioMaestro.setFocusable(false);
        this.FondoInicioMaestro.setVisible(false);
        this.FondoCrearP.setEnabled(true);
        this.FondoCrearP.setFocusable(true);
        this.FondoCrearP.setVisible(true);
    }//GEN-LAST:event_CrearBtnActionPerformed

    private void PublicacionVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublicacionVolverActionPerformed
        this.FondoInicioMaestro.setEnabled(true);
        this.FondoInicioMaestro.setFocusable(true);
        this.FondoInicioMaestro.setVisible(true);
        this.FondoVerPublicacion.setEnabled(false);
        this.FondoVerPublicacion.setFocusable(false);
        this.FondoVerPublicacion.setVisible(false);
    }//GEN-LAST:event_PublicacionVolverActionPerformed

    private void CancelarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarEditActionPerformed
        this.FondoVerPublicacion.setEnabled(true);
        this.FondoVerPublicacion.setFocusable(true);
        this.FondoVerPublicacion.setVisible(true);
        this.FondoEdit.setEnabled(false);
        this.FondoEdit.setFocusable(false);
        this.FondoEdit.setVisible(false);
    }//GEN-LAST:event_CancelarEditActionPerformed

    private void EditarPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPublicacionActionPerformed
        this.FondoVerPublicacion.setEnabled(false);
        this.FondoVerPublicacion.setFocusable(false);
        this.FondoVerPublicacion.setVisible(false);
        this.FondoEdit.setEnabled(true);
        this.FondoEdit.setFocusable(true);
        this.FondoEdit.setVisible(true);
        this.jTextAreaTituloEdit.setText(this.jTextAreaTitulo.getText());
        this.jTextAreaPubliEdit.setText(this.jTextAreaPubli.getText());
    }//GEN-LAST:event_EditarPublicacionActionPerformed

    private void ConfirmarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarEditActionPerformed
        
        try {
            this.control.EditPubli(this.PubliActual.getID(),this.jTextAreaTituloEdit.getText(),this.jTextAreaPubliEdit.getText());
            
        } catch (SQLException ex) {
            Logger.getLogger(Maestro.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.FondoVerPublicacion.setEnabled(true);
        this.FondoVerPublicacion.setFocusable(true);
        this.FondoVerPublicacion.setVisible(true);
        this.FondoEdit.setEnabled(false);
        this.FondoEdit.setFocusable(false);
        this.FondoEdit.setVisible(false);
        this.jTextAreaTitulo.setText(this.jTextAreaTituloEdit.getText());
        this.jTextAreaPubli.setText(this.jTextAreaPubliEdit.getText());
        this.jPanelInicio.removeAll();
        this.Post(this.usuario.getName(), 1000);
    }//GEN-LAST:event_ConfirmarEditActionPerformed

    private void EliminarPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarPublicacionActionPerformed
        
        try {
            this.control.DeletePubli(this.PubliActual.getID());
            
        } catch (SQLException ex) {
            Logger.getLogger(Maestro.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.FondoInicioMaestro.setEnabled(true);
        this.FondoInicioMaestro.setFocusable(true);
        this.FondoInicioMaestro.setVisible(true);
        this.FondoVerPublicacion.setEnabled(false);
        this.FondoVerPublicacion.setFocusable(false);
        this.FondoVerPublicacion.setVisible(false);
        this.jPanelInicio.removeAll();
        this.Post(this.usuario.getName(), 1000);
    }//GEN-LAST:event_EliminarPublicacionActionPerformed

    private void ConfirmarCrearPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarCrearPActionPerformed
        
        String[] options = {"Principiante", "Intermedio", "Avanzado"};
        int seleccion = JOptionPane.showOptionDialog(null, "¿Cuál es la dificultad de esta publicación?", "Nivel", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,null, options, options[0]);            
        if(seleccion != -1){
            this.FondoInicioMaestro.setEnabled(true);
            this.FondoInicioMaestro.setFocusable(true);
            this.FondoInicioMaestro.setVisible(true);
            this.FondoCrearP.setEnabled(false);
            this.FondoCrearP.setFocusable(false);
            this.FondoCrearP.setVisible(false);
            try {
                this.control.InsertPubli(this.usuario.getID(), this.jTextAreaTituloCrearP.getText(), options[seleccion], this.jTextAreaPubliCrearP.getText());
            } catch (SQLException ex) {
                Logger.getLogger(Maestro.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jTextAreaTituloCrearP.setText("");
            this.jTextAreaPubliCrearP.setText("");
            this.jPanelInicio.removeAll();
            this.Post(this.usuario.getName(), 1000);
        }
    }//GEN-LAST:event_ConfirmarCrearPActionPerformed

    private void CancelarCrearPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarCrearPActionPerformed
        this.FondoInicioMaestro.setEnabled(true);
        this.FondoInicioMaestro.setFocusable(true);
        this.FondoInicioMaestro.setVisible(true);
        this.FondoCrearP.setEnabled(false);
        this.FondoCrearP.setFocusable(false);
        this.FondoCrearP.setVisible(false);
    }//GEN-LAST:event_CancelarCrearPActionPerformed

    private void CarrarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrarSesionBtnActionPerformed
        Inicio pantalla = new Inicio(this.control);
        pantalla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CarrarSesionBtnActionPerformed
    
    private void Post(String Name, int limit){
        try {
            ArrayList<Publicacion> list = this.control.SelectPubli(Name, limit);
            for (int i = 0; i < list.size(); i++) {
                Publicacion publi = list.get(i);
                publi.setText("<html><p></p><p>Autor: "+publi.getAutor()+"</p><p>"+publi.getTitulo()+"</p><p>Dificultad: "+publi.getDificultad()+"</p><p></p><p></p></html>");
                publi.setFont(new java.awt.Font("Century Gothic", 1, 18));
                publi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
                publi.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent e) {
                        FondoInicioMaestro.setEnabled(false);
                        FondoInicioMaestro.setFocusable(false);
                        FondoInicioMaestro.setVisible(false);
                        FondoVerPublicacion.setEnabled(true);
                        FondoVerPublicacion.setFocusable(true);
                        FondoVerPublicacion.setVisible(true);
                        jTextAreaPubli.setText(publi.getTexto());
                        jTextAreaTitulo.setText(publi.getTitulo());
                        PubliActual = publi;
                    }
                });
                this.jPanelInicio.add(list.get(i));
            }
            this.jPanelInicio.revalidate();
            this.jPanelInicio.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(Maestro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarCrearP;
    private javax.swing.JButton CancelarEdit;
    private javax.swing.JButton CarrarSesionBtn;
    private javax.swing.JButton ConfirmarCrearP;
    private javax.swing.JButton ConfirmarEdit;
    private javax.swing.JButton CrearBtn;
    private javax.swing.JButton CuentaBtn;
    private javax.swing.JButton EditarPublicacion;
    private javax.swing.JButton EliminarPublicacion;
    private javax.swing.JPanel FondoCrearP;
    private javax.swing.JPanel FondoEdit;
    private javax.swing.JPanel FondoInicioMaestro;
    private javax.swing.JPanel FondoVerPublicacion;
    private javax.swing.JPanel InicioAprendiz;
    private javax.swing.JLayeredPane LayeredPane;
    private javax.swing.JButton PublicacionVolver;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JScrollPane jScrollPaneComent;
    private javax.swing.JScrollPane jScrollPaneInicio;
    private javax.swing.JScrollPane jScrollPanePubli;
    private javax.swing.JScrollPane jScrollPanePubliCrearP;
    private javax.swing.JScrollPane jScrollPanePubliEdit;
    private javax.swing.JScrollPane jScrollPaneTitulo;
    private javax.swing.JScrollPane jScrollPaneTituloCrearP;
    private javax.swing.JScrollPane jScrollPaneTituloEdit;
    private javax.swing.JTextArea jTextAreaComent;
    private javax.swing.JTextArea jTextAreaPubli;
    private javax.swing.JTextArea jTextAreaPubliCrearP;
    private javax.swing.JTextArea jTextAreaPubliEdit;
    private javax.swing.JTextArea jTextAreaTitulo;
    private javax.swing.JTextArea jTextAreaTituloCrearP;
    private javax.swing.JTextArea jTextAreaTituloEdit;
    // End of variables declaration//GEN-END:variables
}
